In [1]:
import numpy as np

In [2]:
iniList = [1,2,3,4,5]

In [3]:
npArray = np.array(iniList)

In [12]:
npArray

array([1, 2, 3, 4, 5])

In [44]:
duaD = np.array([[1,2,3],
                 [4,5,6]])

duaDd = np.array([[1,1,1],
                 [1,1,1],
                 [1,1,1]])

duaDa = np.array([[2,2],
                 [2,2],
                 [2,2]])

In [30]:
print(np.add(duaD,duaDd))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [32]:
print(duaD + duaDd)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [62]:
print("shape duaD : ", duaD.shape)
print("shape duaDa : ", duaDa.shape)

shape duaD :  (2, 3)
shape duaDa :  (3, 2)


In [67]:
print(np.dot(duaD, duaDa)) #Perkalian Dot Product
print("\nshape setelah dot product :", np.dot(duaD, duaDa).shape)

[[12 12]
 [30 30]]

shape setelah dot product : (2, 2)


dot product : (2, 3) * (3, 2) = (2, 2)

In [49]:
print(np.sum(duaD)) #Sum semua

21


In [53]:
print(np.sum(duaD, axis=1)) #Sum Perbaris

[ 6 15]


In [54]:
print(np.sum(duaD, axis=0)) #Sum Perkolom

[5 7 9]


In [56]:
print(np.mean(duaD)) #Mean Semua

3.5


In [59]:
print(np.mean(duaD, axis=0)) #Mean Perkolom

[2.5 3.5 4.5]


In [60]:
print(np.mean(duaD, axis=1)) #Sum Perbaris

[2. 5.]


In [74]:
print("shape duaD : ", duaD.shape)

shape duaD :  (2, 3)


In [77]:
duaD

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
a = np.reshape(duaD, (3,2))
a

array([[1, 2],
       [3, 4],
       [5, 6]])